ChurchManagementSystem.Web/Models/ResetForgotPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ChurchManagementSystem.Web.Models
{
    public class ResetForgotPasswordViewModel
    {
        public string Email { get; set; }
        [Required]
        public string Token { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        [Compare("Password", ErrorMessage = "Password and Confirmation Password must match.")]
        public string Confirm { get; set; }

    }
}

ChurchManagementSystem.Web/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;

using CSharpFunctionalExtensions;

using ChurchManagementSystem.Web.Extentions;
using ChurchManagementSystem.Web.Models;
using ChurchManagementSystem.Web.Services.Access;
using ChurchManagementSystem.Web.Services.UserProfile;
using ChurchManagementSystem.Web.Services.Users;

using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ChurchManagementSystem.Web.Controllers
{
    [AllowAnonymous]
    public class AccountsController : Controller
    {
        private readonly IAccessManagement _accessManagement;
        private readonly IUserManagement _userManagement;
        private readonly IUserProfileManagement _userProfileManagement;

        public AccountsController(IAccessManagement accessManagement, IUserManagement userManagement,
            IUserProfileManagement userProfileManagement)
        {
            _accessManagement = accessManagement;
            _userManagement = userManagement;
            _userProfileManagement = userProfileManagement;
        }

        public IActionResult Login(string returnUrl = null)
        {                                                                    
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto model)
        {
            if (ModelState.IsValid)
            {
                var request = new LoginRequest
                {
                    Login = new Login
                    {
                        ClientId = AppsettingsManager.Fetch("ClientId"),
                        ClientSecret = AppsettingsManager.Fetch("ClientSecret"),
                        Email = model.Email,
                        Password = model.Password,
                        Scope = AppsettingsManager.Fetch("Scope")
                    }
                };

                var rsp = await _accessManagement.Login(request);

                if (rsp != null)
                {
                    if (rsp.Error != null)
                    {
                        ViewBag.Msg = rsp?.Error_description;

                        return View();
                    }

                    // compose identity
                    var identity = SignInUser(rsp, model.Email).Result;
                    Result validateResponse = Result.Combine(identity);
                    if (validateResponse.IsFailure)
                    {
                        ViewBag.Msg = validateResponse.Error;
                        return View();
                    }

                    // sign in user
                    var principal = new ClaimsPrincipal(identity.Value);
                    var authProperties = new AuthenticationProperties() { IsPersistent = false };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(identity.Value),
                        authProperties);

                    Thread.CurrentPrincipal = principal;

                    //Save token in session object
                    HttpContext.Session.SetString("JWToken", rsp.Access_token);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Msg = "Can't Login At the Moment";

                    return View();
                }
            }

            return View("Index");
        }
                                                                       
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            var request = new LogoutRequest
            {
                ClientSecret = "",
                ClientId = "",
                Token = HttpContext.Session.GetString("JWToken")
            };

            var rsp = await _accessManagement.Logout(request);

            if (rsp != null && !rsp.HasErrors)
            {
                HttpContext.Session.Clear();

                await HttpContext.SignOutAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme);

                return RedirectToAction("Index", "Home");
            }

            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Register()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult Register(string test)
        //{
        //    ViewBag.Msg = "Can't Register at the Moment...";

        //    return View();
        //}

        //public IActionResult ForgotPassword()
        //{
        //    return View();
        //}

        [HttpGet("ForgotPassword/{email}")]
        public async Task<IActionResult> ForgotPassword(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                ViewBag.Msg = "The email field is required";
                return View();
            }

            var request = new ForgotPasswordRequest
            {
                RecoveryEmail = email
            };

            var rsp = await _userProfileManagement.ForgotPassword(request);

            if (rsp != null && !rsp.HasErrors)
            {
                ViewBag.Info = $"We have sent a mail to {email} successfully";

                ViewBag.Email = email;

                return View();
            }
            else
            {
                ViewBag.Msg = rsp?.Errors[0].ErrorMessage ?? "Mail Can't be Sent At the Moment";

                return View();
            }
        }

        public IActionResult ResetForgotPassword(string email)
        {
            var model = new ResetForgotPasswordViewModel
            {
                Email = email
            };

            return View(model);
        }

        [HttpGet("ResetForgotPassword/{email}")]
        public async Task<IActionResult> ResetForgotPassword(ResetForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var request = new ResetForgotPasswordRequest
                {
                    NewPassword = model.Password,
                    RecoveryEmail = model.Email,
                    Token = model.Token
                };

                var rsp = await _userProfileManagement.ResetForgotPassword(request);

                if (rsp != null && !rsp.HasErrors)
                {
                    return RedirectToAction("ResetForgotPasswordSuccess");
                }
                else
                {
                    ViewBag.Msg = rsp?.Errors[0].ErrorMessage ?? "Password Can't be changed At the Moment";

                    return View();
                }
            }

            return View();
        }

        public IActionResult ResetForgotPasswordSuccess()
        {
            return View();
        }

        private async Task<Result<ClaimsIdentity>> SignInUser(LoginResponse userProfile, string email)
        {
            var stream = userProfile.Access_token;
            var handler = new JwtSecurityTokenHandler();
            var tokens = handler.ReadToken(stream) as JwtSecurityToken;

            var roleId = tokens.Claims.First(claim => claim.Type == "RoleId").Value;
            if (roleId != "1")
            {
                return Result.Failure<ClaimsIdentity>($"Your profile does not have the permission to access to this portal.");
            }

            //var GetRoles = await _userManagement.GetUserRoles(stream);
            //if (GetRoles == null || GetRoles.HasErrors)
            //    return Result.Failure<ClaimsIdentity>($"Can't Access Roles in the system at the moment");

           // var roles = GetRoles.Data;

            var claims = new List<Claim>
            {
                new Claim(ChurchManagementSystemClaimTypes.UserName, email),
                new Claim(ChurchManagementSystemClaimTypes.FirstName, tokens.Claims.First(claim => claim.Type == "FirstName").Value),
                new Claim(ChurchManagementSystemClaimTypes.LastName, tokens.Claims.First(claim => claim.Type == "LastName").Value),
                new Claim(ChurchManagementSystemClaimTypes.FullName, $"{tokens.Claims.First(claim => claim.Type == "LastName").Value} {tokens.Claims.First(claim => claim.Type == "FirstName").Value}"),
                new Claim(ChurchManagementSystemClaimTypes.Token_type, userProfile.Token_type),
                new Claim(ChurchManagementSystemClaimTypes.Access_token, userProfile.Access_token),
                new Claim(ChurchManagementSystemClaimTypes.Expires_in, userProfile.Expires_in.ToString()),
                new Claim(ChurchManagementSystemClaimTypes.RoleId, tokens.Claims.First(claim => claim.Type == "RoleId").Value),
               // new Claim(ChurchManagementSystemClaimTypes.RoleName, roles.FirstOrDefault(a => a.RoleId == int.Parse(tokens.Claims.First(claim => claim.Type == "RoleId").Value))?.Name),
                new Claim(ChurchManagementSystemClaimTypes.UserId, tokens.Claims.First(claim => claim.Type == "UserId").Value),
                new Claim(ChurchManagementSystemClaimTypes.HasWebPortalAccess, tokens.Claims.First(claim => claim.Type == "HasWebPortalAccess").Value),

               // new Claim(ClaimTypes.Role, roles.FirstOrDefault(a => a.RoleId == int.Parse(tokens.Claims.First(claim => claim.Type == "RoleId").Value))?.Name)
            };

            // compose identity
            var identity = new ClaimsIdentity(DefaultAuthenticationTypes.ApplicationCookie);
            identity.AddClaims(claims);

            return Result.Success(identity);

ChurchManagementSystem.Web/Views/Accounts/ForgotPassword.cshtml
@{
    ViewData["Title"] = "ForgotPassword";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- [ Form ] Start -->
<form method="post" class="card">
    <div class="p-4 p-sm-5">
        <!-- [ Logo ] Start -->
        <div class="d-flex justify-content-center align-items-center pb-2 mb-4">
            <div class="ui-w-60">
                <div class="w-100 position-relative">
                    <img src="~/img/logo-dark.png" alt="Brand Logo" class="img-fluid">
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- [ Logo ] End -->

        @if (!string.IsNullOrEmpty(ViewBag.Info))
        {
            <div class="alert alert-success alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.Info
            </div>

            <div class="form-group">
                <input name="email" type="email" class="form-control" placeholder="receiver email" required value="@ViewBag.Email" readonly disabled>
                <div class="clearfix"></div>
            </div>

            <!--<button type="submit" class="btn btn-primary btn-block">Resend Email</button>-->
            <a asp-controller="Accounts"
               asp-action="ForgotPassword"
               asp-route-email="@ViewBag.Email" style="float: right; font-weight: bold; color: rgba(240, 73, 35, 0.8);">Resend Email</a>
            <!--<a asp-controller="Accounts" asp-action="ResetForgotPassword" asp-route-email="@ViewBag.Email" class="btn btn-round btn-block btn-success mt-3">I Have Code</a>-->
        }
        else
        {
            @if (!string.IsNullOrEmpty(ViewBag.Msg))
            {
                <span class="text-danger">@ViewBag.Msg</span>
            }

            <h5 class="text-center text-muted font-weight-normal mb-4">Reset Your Password</h5>
            <hr class="mt-0 mb-4">
            <p>Enter your email address and we will send you a link to reset your password.</p>
            <div class="form-group">
                <input name="email" type="email" class="form-control" placeholder="Enter your email address" required>
                <div class="clearfix"></div>
            </div>

            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
        }

    </div>
</form>
<!-- [ Form ] End -->

ChurchManagementSystem.Web/Views/Accounts/Login.cshtml
@*@model Feels.Services.Access.LoginDto*@

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- [ Logo ] Start -->
<div class="d-flex justify-content-center align-items-center">
    <div class="ui-w-60">
        <div class="w-100 position-relative">
            <img src="~/img/feelsLogo.png" alt="Brand Logo" class="img-fluid">
        </div>
    </div>
</div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0&appId=2070441116535138&autoLogAppEvents=1" nonce="PHFWrd8p"></script>
<script>

    function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().
        console.log('statusChangeCallback');
        console.log(response);                   // The current login status of the person.
        if (response.status === 'connected') {   // Logged into your webpage and Facebook.
            testAPI();
        } else {                                 // Not logged into your webpage or we are unable to tell.
            console.log('Code should not reach here')
            document.getElementById('status').innerHTML = 'Please log ' +
                'into this webpage.';
        }
    }


    function checkLoginState() {               // Called when a person is finished with the Login Button.
        console.log("Checking login state on click");
        FB.getLoginStatus(function (response) {   // See the onlogin handler
            if (response.status === 'connected') {
                console.log(response.authResponse.accessToken);
            }
            statusChangeCallback(response);
        });
    }

    window.fbAsyncInit = function () {
        FB.init({
            appId: '2070441116535138',
            cookie: true,                     // Enable cookies to allow the server to access the session.
            xfbml: true,                     // Parse social plugins on this webpage.
            version: 'v9.0'           // Use this Graph API version for this call.
        });

        console.log("FB window initialized");

        FB.getLoginStatus(function (response) {   // Called after the JS SDK has been initialized.
            statusChangeCallback(response);        // Returns the login status.
        });
    };

    function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me?fields=email,name,birthday,hometown', function (response) {
            console.log('Successful login for: ' + response.name);
            str = JSON.stringify(response);
            console.log('Full response ' + str);
            document.getElementById('status').innerHTML =
                'Thanks for logging in, ' + response.name + '!';
        });
    }

</script>
<!-- [ Logo ] End -->
<!-- [ Form ] Start -->
<form method="post" class="my-5">
    <div asp-validation-summary="All" class="text-danger"></div>
    @if (!string.IsNullOrEmpty(ViewBag.Msg))
    {
        <span class="text-danger">@ViewBag.Msg</span>
    }
    <div class="form-group">
        <label class="form-label">Email</label>
        <input name="Email" type="email" class="form-control">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label class="form-label d-flex justify-content-between align-items-end">
            <span>Password</span>
            <a asp-action="ForgotPassword" asp-controller="Accounts" class="d-block small">Forgot password?</a>
        </label>
        <input name="Password" type="password" class="form-control">
        <div class="clearfix"></div>
    </div>
    <div class="d-flex justify-content-between align-items-center m-0">
        @*<label class="custom-control custom-checkbox m-0">
                <input type="checkbox" class="custom-control-input">
                <span class="custom-control-label">Remember me</span>
            </label>*@
        <button type="submit" class="btn btn-primary">Login</button>
        @* <div class="fb-login-button" data-width="" data-size="large" data-button-type="login_with" data-layout="rounded" data-auto-logout-link="false" data-use-continue-as="true"></div>*@
        @* <div class="fb-login-button" data-width="10" data-size="small" data-button-type="login_with" data-layout="rounded" data-auto-logout-link="false" data-use-continue-as="true"></div>*@
        @*<div class="fb-login-button" data-width="10" data-size="medium" data-button-type="continue_with" data-layout="default" data-auto-logout-link="false" data-use-continue-as="true"></div>*@
        <div class="fb-login-button" scope="public_profile,email" onlogin="checkLoginState()" data-width="10" data-size="medium" data-button-type="login_with" data-layout="rounded" data-auto-logout-link="false" data-use-continue-as="true"></div>
    </div>
    <div id="status">
    </div>
</form>
<!-- [ Form ] End -->

<div class="text-center text-muted">
    Don't have an account yet?
    <a asp-action="Register" asp-controller="Accounts">Register</a>
</div>

ChurchManagementSystem.Web/Views/Accounts/Logout.cshtml
@{
    ViewData["Title"] = "Logout";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

ChurchManagementSystem.Web/Views/Accounts/Register.cshtml
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- [ Logo ] Start -->
<div class="d-flex justify-content-center align-items-center">
    <div class="ui-w-60">
        <div class="w-100 position-relative">
            <img src="~/img/logo-dark.png" alt="Brand Logo" class="img-fluid">
        </div>
    </div>
</div>
<!-- [ Logo ] End -->
<!-- [ Form ] Start -->
<form method="post" class="my-5">
    <div asp-validation-summary="All" class="text-danger"></div>
    @if (!string.IsNullOrEmpty(ViewBag.Msg))
    {
        <span class="text-danger">@ViewBag.Msg</span>
    }

    <div class="form-group">
        <label class="form-label">Your name</label>
        <input type="text" class="form-control">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label class="form-label">Your email</label>
        <input type="text" class="form-control">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label class="form-label">Password</label>
        <input type="password" class="form-control">
        <div class="clearfix"></div>
    </div>
    <button type="submit" class="btn btn-primary btn-block mt-4">Register</button>
   
</form>
<!-- [ Form ] End -->

<div class="text-center text-muted">
    Already have an account?
    <a asp-action="Login" asp-controller="Accounts">Login</a>
</div>

ChurchManagementSystem.Web/Views/Accounts/ResetForgotPassword.cshtml
@model ResetForgotPasswordViewModel
@{
    ViewData["Title"] = "ResetForgotPassword";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- [ Form ] Start -->
<form method="post" class="card">
    <div class="p-10 p-md-5">
        <!-- [ Logo ] Start -->
        <div class="d-flex justify-content-center align-items-center pb-2 mb-4">
            <div class="ui-w-60">
                <div class="w-100 position-relative">
                    <img src="~/img/logo-dark.png" alt="Brand Logo" class="img-fluid">
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- [ Logo ] End -->

        @if (!string.IsNullOrEmpty(ViewBag.Msg))
        {
            <span class="text-danger">@ViewBag.Msg</span>
        }

        <h5 class="text-center text-muted font-weight-normal mb-4">Reset Your Password</h5>
        <hr class="mt-0 mb-4">
        <p>Enter the token sent to your mail and then your new password.</p>
        <div class="form-group">
            <input asp-for="Email" type="email" class="form-control" placeholder="Enter your email address" required hidden value="@Model.Email">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <input asp-for="Token" type="text" class="form-control" placeholder="Enter token " required>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <input asp-for="Password" type="password" class="form-control" placeholder="Enter Password " required>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <input asp-for="Confirm" type="password" class="form-control" placeholder="Confirm Password " required>
            <div class="clearfix"></div>
        </div>


        <button type="submit" class="btn btn-primary btn-block">Change Password</button>

    </div>
</form>
<!-- [ Form ] End -->

ChurchManagementSystem.Web/Views/Accounts/ResetForgotPasswordSuccess.cshtml
@{
    ViewData["Title"] = "ResetForgotPasswordSuccess";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- [ Form ] Start -->
<div class="card">
    <div class="p-4 p-sm-5">
        <div class="display-1 lnr lnr-checkmark-circle text-center text-success mb-4"></div>
        <p class="text-center text-big mb-4">Your Password Was Changed successfully.</p>
        <a asp-action="Login" asp-controller="Accounts" class="btn btn-primary btn-block">Proceed to your account</a>
    </div>
</div>
<!-- [ Form ] End -->